version: '3.9'

services:
  foundry:
    image: felddy/foundryvtt:release

    # TODO: Sort out network and port-forwarding
    hostname:     foundryvtt
    network_mode: host

    init:    true
    restart: "unless-stopped"

    volumes:
      - type:   bind
        source: ~/fvtt-on-rpi/data
        target: /data

    environment:
      # Foundry credentials
      FOUNDRY_USERNAME: <your foundry username>
      FOUNDRY_PASSWORD: <your foundry password>

      # Server admin key
      FOUNDRY_ADMIN_KEY: <admin key for your server>

      # Set to same as the server UID and GID (probably 1000 & 1000)
      FOUNDRY_UID: <server user id>
      FOUNDRY_GID: <server group id>
